spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    include: jwt, bcrypt

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    context-path: /api
