server:
  port: 8080

spring:
  profiles:
    include: jwt, bcrypt
#    active: local
    group:
      dev: log-dev
      prod: log-prod
      test: test

logging.level:
  org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: real
